---
title: "Exploratory Data Analysis"
author: "Group 6"
output: pdf_document
---

```{r setup, include=FALSE}
# setup chunks
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", warning = F, message = F)
# load libaries
library(tidyverse)
library(grid)
library(patchwork)
# load helper scripts
source(file = "R/wrangle.R")
source(file = "R/visualization.R")
```

```{r}
# load rookies datasets
df_pitcher_rookies <- read_csv("data/rookie-pitchers.csv")
df_position_rookies <- read_csv("data/rookie-positions.csv")
# load retired datasets
df_pitcher_retired <- read_csv("data/retired-pitchers.csv")
df_position_retired <- read_csv("data/retired-positions.csv")
```

```{r}
# select appopriate columns
wrangle_ <- function(dataset){
  colnames(dataset)[3] <- "WAR"
  dataset %>% select(WAR, Year)
}
# obtain summary of WAR: median and variance
summary_ <- function(dataset){
  dataset %>% 
    group_by(Year) %>%
    summarize(median_WAR = median(WAR), mean_WAR = mean(WAR), sd_WAR = sqrt(var(WAR))) %>%
    mutate(threshold1 = mean_WAR - sd_WAR, threshold2 = median_WAR - sd_WAR)
}
```

```{r}
# get wrnagled datasets
pitcher_rookies <- wrangle_(df_pitcher_rookies)
position_rookies <- wrangle_(df_position_rookies)
pitcher_retired <- wrangle_(df_pitcher_retired)
position_retired <- wrangle_(df_position_retired)
# get summaries
pitcher_rookies_summary <- summary_(pitcher_rookies)
position_rookies_summary <- summary_(position_rookies)
pitcher_retired_summary <- summary_(pitcher_rookies)
position_retired_summary <- summary_(pitcher_rookies)
```

```{r}
# get summaries
pitcher_rookies_summary <- pitcher_rookies_summary %>% select(Year, threshold1, threshold2)
position_rookies_summary <- position_rookies_summary %>% select(Year, threshold1, threshold2)
pitcher_retired_summary <- pitcher_retired_summary %>% select(Year, threshold1, threshold2)
position_retired_summary <- position_retired_summary %>% select(Year, threshold1, threshold2)
```


```{r}
append_thresholds <- function(dataset, summary_dataset, threshold_index){
  above_threshold <- rep(NA, nrow(dataset))
  for(i in 1:nrow(dataset)){
    year <- as.numeric(dataset[i,2])
    # threshold_index = 2 => mean
    # threshold_index = 3 => median
    above_threshold[i] <- (dataset[i,1] > summary_dataset[year - 1968, threshold_index])
  }
  dataset <- cbind(dataset,above_threshold)
  dataset
}
```

```{r}
# check which players cross that year's threshold
pitcher_retired <- append_thresholds(pitcher_retired, pitcher_rookies_summary, 2)
pitcher_retired <- append_thresholds(pitcher_retired, pitcher_rookies_summary, 3)
colnames(pitcher_retired)[3] <- "above_mean_threshold"
colnames(pitcher_retired)[4] <- "above_median_threshold"
```

```{r}
# check which players cross that year's threshold
position_retired <- append_thresholds(position_retired, position_rookies_summary, 2)
position_retired <- append_thresholds(position_retired, position_rookies_summary, 3)
colnames(position_retired)[3] <- "above_mean_threshold"
colnames(position_retired)[4] <- "above_median_threshold"
```

```{r}
cbns_retired_mean <- count(position_retired,above_mean_threshold)
cbns_retired_median <-count(position_retired,above_median_threshold)
# normalize
cbns_retired_mean[,2] <- cbns_retired_mean[,2]/sum(cbns_retired_mean$n)
cbns_retired_median[,2] <- cbns_retired_median[,2]/sum(cbns_retired_median$n)
```

```{r}
#cbns_retired_mean
#cbns_retired_median
```

```{r}
count_cbns <- function(dataset){
  dataset %>% 
    group_by(Year) %>%
    summarize(count_cbns_mean = sum(above_mean_threshold), 
              count_cbns_median = sum(above_median_threshold))
}
```

```{r}
cbns_pitchers <- count_cbns(pitcher_retired)
cbns_position <- count_cbns(position_retired)
```

```{r}
plot_cbns <- function(dataset, title, color){
  ggplot(data = dataset, aes(x = Year, y = count_cbns_mean)) + 
    stat_smooth(method = "lm", se = F, color = paste(color)) +
    geom_point(color = paste(color)) +
    labs(title = paste(title))
}
```

## Histograms of WAR 

```{r, fig.height = 5}
hist1 <- hist.var("WAR", pitcher_rookies, title = "Histogram 1")
hist2 <- hist.var("WAR", position_rookies, title = "Histogram 2")
hist1/hist2
```

\newpage

## Title of this page

Some other thing here

```{r, fig.height = 3}
plot_cbns(cbns_position, "Coulda-Beens: Position Players", "dodgerblue3")
```

Something here

```{r, fig.height = 3}
plot_cbns(cbns_pitchers, "Coulda-Beens: Pitcher Players", "deeppink1")
```






