---
title: "Modeling"
author: "Group 6"
output: pdf_document
---

```{r setup, include=FALSE}
# setup chunks
knitr::opts_chunk$set(echo = F, fig.align = "center", warning = F, message = F, fig.height = 4)
# load libaries
library(tidyverse)
library(grid)
library(gridExtra)
library(patchwork)
library(ISLR)
# load helper scripts
source(file = "R/wrangle.R")
source(file = "R/model.R")
source(file = "R/visualization.R")
source(file = "R/threshold.R")
# global parameters
bplot <- T
bloud <- T
```

```{r}
#=============================#
#       Import Datasets       #
#=============================#
# Load rookies datasets
df_pit_rkes <- read_csv("data/rookie-pitcher.csv")
df_pos_rkes <- read_csv("data/rookie-position.csv")
# Load retirees datasets
df_pit_ret <- read_csv("data/retirees-pitcher.csv")
df_pos_ret <- read_csv("data/retirees-position.csv")
# Find number of retirees by year
num_retirees <- total_retirees_by_yr(df_pit_ret, df_pos_ret)
num_retirees <- data.frame(retirees = num_retirees$retirees)
# Create list of datasets for ease of function input
ls_datasets <- list(df_pos_rkes, df_pos_ret, df_pit_rkes, df_pit_ret, num_retirees)
```

```{r, cache = T}
#==============================#
#       Position Players       #
#==============================#
# Obtain wrangled datasets
pos_rkes <- wrangle_init(df_pos_rkes)
pos_ret <- wrangle_init(df_pos_ret)
# Get thresholds in each year
pos_rkes_thresholds <- find_thresholds(pos_rkes)
# See and record which players cross that year's threshold
pos_ret <- compare_thresholds(pos_ret, pos_rkes_thresholds)
```

```{r, cache = T}
#==============================#
#        Pitcher Players       #
#==============================#
# Obtain wrangled datasets
pit_rkes <- wrangle_init(df_pit_rkes)
pit_ret <- wrangle_init(df_pit_ret)
# Get thresholds in each year
pit_rkes_thresholds <- find_thresholds(pit_rkes)
# See and record which players cross that year's threshold
pit_ret <- compare_thresholds(pit_ret, pit_rkes_thresholds)
```

# The Couldabeen Classification Problem

```{r, fig.height = 6}
# Density plot of rookie and retired pitchers 
pitcher_density <- ggplot() +
  geom_density(data = pit_ret, aes_string(x = "WAR"), color = "salmon") +
  geom_density(data = pit_rkes, aes_string(x = "WAR"), color = "skyblue3") +
  geom_vline(xintercept = median(pit_rkes$WAR), color = "skyblue3") +
  labs(title = "Pitchers")
# Density plot of rookie position players and retired position players 
position_density <- ggplot() +
  geom_density(data = pos_ret, aes_string(x = "WAR"), color = "salmon") +
  geom_density(data = pos_rkes, aes_string(x = "WAR"), color = "skyblue3") +
  geom_vline(xintercept = median(pos_rkes$WAR), color = "skyblue3") +
  labs(title = "Position")
# Plot
if(bplot){grid.arrange(pitcher_density, position_density, nrow = 2)}
```

\newpage

```{r, echo = T}
#===================================#
#        Counting: Couldabeens      #
#===================================#
# Combine the threshold-classified retiree datasets
retirees <- rbind(pit_ret,pos_ret)
# Count couldabeens
couldabeens <- count_cbns(retirees)
```

```{r, echo = F}
head(couldabeens)
```

## First Look: A Logistic Model


```{r, fig.width = 6}
dataset <- pit_ret
if(bplot){plot_logmodel(dataset)}
```

```{r}
model_log <- logistic_model(pit_ret)
if(bloud){summary(model_log)}
```

```{r}
#===================================#
#      Proportions: Couldabeens     #
#===================================#
# Find number of retirees by year
num_retirees <- total_retirees_by_yr(df_pit_ret, df_pos_ret)
num_retirees <- data.frame(retirees = num_retirees$retirees)
# Append number of retirees that year
couldabeens <- cbind(couldabeens, num_retirees)
# Find proportion of couldabeens : retirees
couldabeens <- couldabeens %>% mutate(prop = cbns/retirees)
```

```{r, echo = F}
head(couldabeens)
```

```{r, echo = T}
#==================#
#     Modeling     #
#==================#
# Partition dataset into years before and after rule
couldabeens_pre <- prerule(couldabeens)
couldabeens_post <- postrule(couldabeens)
# Obtain linear model for pre-rule years
model_pre <- linear_model(couldabeens_pre)
coefs_pre <- model_pre$coefficients
# Obtain linear model for post-rule years
model_post <- linear_model(couldabeens_post)
coefs_post <- model_post$coefficients
# Obtain linear model for all years
model_comp <- linear_model(couldabeens)
coefs_comp <- model_comp$coefficients
```

```{r}
#=======================#
#     Visualization     #
#=======================#



```

\newpage 

## Couldabeens: A Comprehensive Look

```{r}
if(bloud){summary(model_comp)}
```

```{r}
# Plot proportion of couldabeens in post-rule era ()
plot_comp <- plot_props_linear(couldabeens, coefs_post, color = "skyblue2", 
                               title = "Proportion of Couldabeen Retirees")
plot_comp
```


\newpage

## Couldabeens: Pre-rule Era (1969-2002)

```{r}
if(bloud){summary(model_pre)}
```

\bigskip
\bigskip

```{r, fig.cap= "Proportion of Retirees who were Coulabeens prior to the implementation of the Luxury Tax"}
# Plot proportion of couldabeens in pre-rule era ()
plot_pre <- plot_props_linear(couldabeens_pre, coefs_pre, color = "salmon", 
                              title = "Proportion of Couldabeen Retirees (1969-2002)")
plot_pre
```

\newpage

## Couldabeens: Post-rule Era (2003-2018)

```{r}
if(bloud){summary(model_post)}
```

\bigskip
\bigskip

```{r, fig.cap= "Proportion of Retirees who were Coulabeens after the implementation of the Luxury Tax"}
# Plot proportion of couldabeens in post-rule era ()
plot_post <- plot_props_linear(couldabeens_post, coefs_post, color = "skyblue2", 
                               title = "Proportion of Couldabeen Retirees (2003-2018)")
plot_post
```

```{r}
# Simpler implementation?
#plot + stat_smooth(mapping = aes(x = Year, y = prop), data = couldabeens_post, method = "lm", formula = prop ~ Year, se = F)
```

```{r}
# Linear model on couldabeens over all years?
#model_year <- lm(formula = cbns ~ Year, data = couldabeens)
#summary(model_year)
#ggplot() + geom_point(data = couldabeens, aes(x = Year, y= cbns))
```

```{r}
# Logisitic regression model on exceeding the threshold?
#model_year <- glm(formula = count_cbns_mean ~ Year, data = cbns_position, family = "binomial")
#summary(model_year)
```








