---
title: "Baseball Proposal"
output: pdf_document
---

Major League Baseball's "competitive balance tax," first implemented in 2002, has become a favorite subject of outrage among players and fans alike in recent years. On paper, the policy was meant to make the sport more competitive and boost salaries for players on lower-revenue teams. The owners and the players' union would negotiate the largest reasonable amount a team could spend on its roster, and any team that wanted to spend beyond that cap would pay a "tax" (a share of their excess payroll) to be redistributed to the poorer teams. In practice the policy has effectively become a salary cap, particularly after the 2016 renegotiations. In 2018 only two MLB teams out of thirty went over the salary threshold, and only one of those by any significant margin (the team that did so, the Boston Red Sox, unsurprisingly went on to win the World Series). With leaguewide revenue growth far outpacing growth in the revenue cap and most younger players effectively locked out of salary negotiations by free agency rules, players have understandably chafed at the limitation on their salaries, with mutterings of a player strike unless the rule is altered.

But while the depressive effect on players' salaries is not in dispute, the question of whether the rule *hurts the game* (a far graver sin among baseball fans than merely conspiring to lower salaries) is more open. At least in the conventional wisdom, the tax encourages teams to cultivate a massive pool of recruits and then pay the best of them the minimum permitted salary for up to seven years before they age into free agency. Once these players enter free agency, the narrative goes, the team dumps them for younger players whom they can pay the minimum salary. The remainder of their salary cap goes towards retaining a few older superstars with the name recognition to bring in fans, with many good-but-not-Mike-Trout players pushed into early retirement. The implication, then, is that the salary policy "hurts the game" because the MLB is less likely to be putting the best 30 shortstops in the world on the field at any given time. I would like to test this anecdotal observation empirically.



Hypothesis: Since the advent of the competitive balance tax, the number of better players forced into retirement annually will have increased. A "better player forced into retirement" will be defined as a player under the age of 32 who a) left baseball due to their contract not being renewed, rather than injury or personal circumstances, and b) was outperforming the median rookie in their position at the time of their retirement.

Data: Major League Baseball is probably the most rigorously and publicly documented sport in human history, with data available on where every ball hit on every play throughout most of the sport's history landed, so finding our data set shouldn't be hard. I personally propose using baseball-reference.com. This will be a categorization problem, and I expect the variables we use will be Wins Above Replacement, position, age, cause of retirement, and number of years in the MLB (to identify the "median rookie").

This question matters to me because with a handful of historical exceptions, most American sports fans do not care about player salary disputes. The minimum salary in baseball is many times higher than what the vast majority of fans will ever make in a year; the fact that professional athletes often have less than a decade to fund the rest of their lives rarely enters our minds. Team owners have frequently taken advantage of this dynamic to increase their own bargaining power, and thus their profit margins - the MLB is specifically exempted from monopoly and salary-fixing regulations by federal law. If we could provide statistical support for the claim that the salary policy is *hurting the game*, though, fans might actually start to think they have a horse in this race. If a player strike ever comes to the MLB again, fan sentiment could be a very important factor in its success or failure.

Potential problems: The lifespan of the "competitive balance tax" happens to overlap with the "Sabermetrics Revolution," in which statistical analysis has come to play a far greater role in determining team policy, especially draft, trade, and signing decisions. To minimize the confounding effect of this shift, we might need to pick an initial year sometime after the publication of *Moneyball* but before the salary threshold began to play a major role (2005ish?). Determining who qualifies as a "better player forced into retirement" is also somewhat arbitrary, and there are issues like players who were taken out for part of the season or had an unusually good or bad year, but since baseball has a very high number of games per season and this is a comparison across years we shouldn't be too worried.

