---
title: "Modeling (Threshold Analysis)"
author: "Group 6"
output: pdf_document
---

```{r setup, include=FALSE}
# setup chunks
knitr::opts_chunk$set(echo = FALSE, fig.align = "center", warning = F, message = F)
# load libaries
library(tidyverse)
library(grid)
library(patchwork)
library(ISLR)
library(gganimate)
# load helper scripts
source(file = "R/wrangle.R")
source(file = "R/model.R")
source(file = "R/threshold.R")
source(file = "R/visualization.R")
```

```{r}
#=============================#
#       Import Datasets       #
#=============================#
# Load rookies datasets
df_pit_rkes <- read_csv("data/rookie-pitcher.csv")
df_pos_rkes <- read_csv("data/rookie-position.csv")
# Load retirees datasets
df_pit_ret <- read_csv("data/retirees-pitcher.csv")
df_pos_ret <- read_csv("data/retirees-position.csv")
```

```{r}
# In case old retiree data is being used
ret_old <- T
if(ret_old){
  # Load (old) retirees datasets
  df_pit_ret <- read_csv("data/_retirees-pitcher.csv")
  df_pos_ret <- read_csv("data/_retirees-position.csv")
}
```

```{r}
# Find number of retirees by year
num_retirees <- total_retirees_by_yr(df_pit_ret, df_pos_ret)
num_retirees <- data.frame(retirees = num_retirees$retirees)
# Create list of datasets for ease of function input
ls_datasets <- list(df_pos_rkes, df_pos_ret, df_pit_rkes, df_pit_ret, num_retirees)
```

```{r, cache = T}
run_stack <- T
# Create vector of thresholds to be analyzed
threshold_vec <- data.frame(threshold = seq(-2,2,by=0.025))
# Create corrosponding stack of couldabeens under variable threshold
if(run_stack){stack <- create_threshold_stack(ls_datasets, threshold_vec)}
write.csv(stack,"stack_old.csv", row.names = FALSE)
```

```{r}
# Coefficients in a threshold stack
coef_array <- coefs_by_stack(stack, threshold_vec)
write.csv(coef_array,"coefarray_old.csv", row.names = FALSE)
```

```{r}
#coef_array <- read.csv(file = "coefarray.csv")
```

```{r, fig.align = "center"}
coef_plot <- ggplot(data = coef_array) + 
  geom_smooth(mapping = aes(x = threshold, y = coef_yr, color = era), se = F) +
  geom_point(mapping = aes(x = threshold, y = coef_yr, color = era))
coef_plot
```

```{r}
stack <- read_csv("stack.csv")
# Partition dataset into years before and after rule
stack_pre <- prerule(stack)
stack_post <- postrule(stack)
```


```{r, include = F}
# Stack of Threshold plots
plot_all <- plot_stack(stack, 
                       "Proportion of Retired Couldabeens (Variable Classification Threshold)")
plot_pre <- plot_stack(stack_pre, 
                       "Proportion of Retired Couldabeens (Pre-Rule Era)")
plot_post <- plot_stack(stack_post, 
                        "Proportion of Retired Couldabeens (Post-Rule Era)")
# Animations
animation_pre <- plot_pre + transition_time(time = threshold)
# Uncomment the line below and run this chunk to view animation of post-rule thresholds
#animation_pre
animation_post <- plot_post + transition_time(time = threshold)
# Uncomment the line below and run this chunk to view animation of post-rule thresholds
#animation_post
```






