---
title: "Modeling"
author: "Group 6"
output: pdf_document
---

```{r setup, include=FALSE}
# setup chunks
knitr::opts_chunk$set(echo = F, fig.align = "center", warning = F, message = F, fig.height = 4)
# load libaries
library(tidyverse)
library(grid)
library(gridExtra)
library(patchwork)
library(ISLR)
library(factoextra)
# load helper scripts
source(file = "../R/wrangle.R")
source(file = "../R/model.R")
source(file = "../R/visualization.R")
source(file = "../R/threshold.R")
source(file = "../R/null_threshold.R")
# global parameters
bplot <- T
bloud <- T
bhead <- T
```

```{r}
#=============================#
#       Import Datasets       #
#=============================#
# Load rookies datasets
pit_rkes <- read_csv("../data/rookie-pitcher.csv")
pos_rkes <- read_csv("../data/rookie-position.csv")
# Load retirees datasets
pit_ret <- read_csv("../data/retirees-pitcher.csv")
pos_ret <- read_csv("../data/retirees-position.csv")
# Find number of retirees by year
num_retirees <- total_retirees_by_yr(pit_ret, pos_ret)
num_retirees <- data.frame(retirees = num_retirees$retirees)
# Aggregate datasets to compute couldabeens
ls_datasets <- list(pos_rkes, pos_ret, pit_rkes, pit_ret, num_retirees)
```

## Null Threshold

```{r, echo = T}
# Get couldabeens
couldabeens <- couldabeens_null_threshold(ls_datasets)
# Get payroll revenue data
payroll_rev <- read_csv("../data/revenue-payroll.csv")
payroll <- find_labShare(payroll_rev)
```

```{r}
# Get varying couldabeens
couldabeens_var <- read_csv("../data-gen/couldabeens.csv")
# Wrangle
couldabeens_var <- couldabeens_var[which(couldabeens_var$Year >= 1990),]
```

```{r}
ggplot() + 
  geom_point(data = couldabeens, mapping = aes(x = Year, y = prop), color = "blue") +
  geom_point(data = couldabeens_var, mapping = aes(x = Year, y = prop), color = "red")
```

```{r}
# Append payroll data in appopriate year (accounting for lag)
couldabeens <- append_payrolls(couldabeens, payroll, lag = 0)
# Create moneyball variable
couldabeens <- couldabeens %>% 
  mutate(postMoneyball = 1 - (Year < 2004))
```

```{r}
# Remove unused columns
couldabeens <- couldabeens[-c(3)]
# Split data
couldabeens_pre <- couldabeens[which(couldabeens$postMoneyball == 0),]
couldabeens_post <- couldabeens %>% anti_join(couldabeens_pre)
```

```{r}
prep_lm <- function(dataset, cols_removed){
  dataset[-cols_removed]
}
```

## Subset 1

```{r}
dataset1 <- prep_lm(couldabeens_post, c(4,6))
head(dataset1)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset1)
summary(lm1)
```

## Subset 2

```{r}
dataset2 <- prep_lm(couldabeens, c(4))
head(dataset2)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset2)
summary(lm1)
```

\newpage

## Subset 3

```{r}
dataset3 <- prep_lm(couldabeens_post, c(5,6))
head(dataset3)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset3)
summary(lm1)
```

## Subset 4

```{r}
dataset4 <- prep_lm(couldabeens, c(5))
head(dataset4)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset4)
summary(lm1)
```

\newpage

## Subset 5

```{r}
dataset5 <- prep_lm(couldabeens_post, c(5,6))
head(dataset5)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset5)
summary(lm1)
```

## Subset 7

```{r}
dataset7 <- prep_lm(couldabeens_post, c(3,5,6))
head(dataset7)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset7)
summary(lm1)
```

\newpage

## Subset 8

```{r}
dataset8 <- prep_lm(couldabeens, c(3,5))
head(dataset8)
```

```{r}
lm1 <- lm(prop ~ . - Year, data = dataset8)
summary(lm1)
```

\newpage

```{r}
remove_years <- function(dataset, yrs){
  dataset[-which(dataset$Year %in% yrs),]
}
#cbns <- remove_years(couldabeens, c(1994,1995))
```

```{r}
# Create plots
plot_pre <- ggplot(data = couldabeens_pre, mapping = aes(x = Year, color = labShare, y = prop)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F)
plot_post <- ggplot(data = couldabeens_post, mapping = aes(x = Year, color = labShare, y = prop)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F)
```

```{r}
plot_post
```

```{r}
# Create plots
plot_pre <- ggplot(data = couldabeens_post, mapping = aes(x = labShare, y = prop)) + 
  geom_point() + 
  geom_smooth(method = "lm", se = F)
#plot_pre
```

```{r}
if(ncol(couldabeens_post) == 4){couldabeens_post[,4] <- NULL}
lm_post <- lm(prop ~ . - Year - postMoneyball, data = couldabeens_post)
summary(lm_post)
```

```{r}
plot(lm_post)
```


\newpage

# Principal Compenents

```{r}
x <- dataset2[c(2,3,4)]
x
prcomp(x, scale = TRUE)
```


# Resampling

```{r}

```


\newpage

# Year as Predictor: Linear Modeling

```{r, echo = T}
#==================#
#     Modeling     #
#==================#
# Partition dataset into years before and after rule
couldabeens_pre <- prerule(couldabeens)
couldabeens_post <- postrule(couldabeens)
# Obtain linear model for pre-rule years
model_pre <- linear_model(couldabeens_pre)
coefs_pre <- model_pre$coefficients
# Obtain linear model for post-rule years
model_post <- linear_model(couldabeens_post)
coefs_post <- model_post$coefficients
```

\newpage

## Couldabeens: Pre-rule Era (1969-2002)

```{r}
if(bloud){summary(model_pre)}
```

```{r, fig.cap= "Proportion of Retirees who were Coulabeens prior to the implementation of the Luxury Tax"}
# Plot proportion of couldabeens in pre-rule era ()
plot_props_linear(couldabeens_pre, coefs_pre, color = "salmon", 
                              title = "Proportion of Couldabeen Retirees (1969-2002)")
```

\newpage

## Couldabeens: Post-rule Era (2003-2018)

```{r}
if(bloud){summary(model_post)}
```

```{r, fig.cap= "Proportion of Retirees who were Coulabeens after the implementation of the Luxury Tax"}
# Plot proportion of couldabeens in post-rule era ()
plot_post <- plot_props_linear(couldabeens_post, coefs_post, color = "skyblue2", 
                               title = "Proportion of Couldabeen Retirees (2003-2018)")
plot_post
```

\newpage 

## Simpson's Paradox

```{r}
# Obtain linear model for all years
model_comp <- linear_model(couldabeens)
coefs_comp <- model_comp$coefficients
# Colors
col <- "violet"
col1 <- "salmon"
col2 <- "skyblue2"
# Plot proportion of couldabeens in post-rule era ()
plot_comp <- scatter_props(couldabeens, title = "Proportion of Couldabeen Retirees") +
    geom_abline(slope = coefs_comp[2], intercept = coefs_comp[1], color = col) + 
    geom_point(data = couldabeens_pre, mapping = aes(x = Year, y = prop), color = col1) +
    geom_abline(slope = coefs_pre[2], intercept = coefs_pre[1], color = col1) +
    geom_point(data = couldabeens_post, mapping = aes(x = Year, y = prop),color = col2) +
    geom_abline(slope = coefs_post[2], intercept = coefs_post[1], color = col2) + 
    labs(y = "Proportion")
#plot_comp
```

