---
title: "Modeling"
author: "Group 6"
output: pdf_document
---

```{r setup, include=FALSE}
# setup chunks
knitr::opts_chunk$set(echo = F, fig.align = "center", warning = F, message = F, fig.height = 4)
# load libaries
library(tidyverse)
library(grid)
library(gridExtra)
library(patchwork)
library(ISLR)
# load helper scripts
source(file = "../R/wrangle.R")
source(file = "../R/model.R")
source(file = "../R/visualization.R")
source(file = "../R/threshold.R")
# global parameters
bplot <- T
bloud <- T
bhead <- T
```

```{r}
#=============================#
#       Import Datasets       #
#=============================#
# Load rookies datasets
df_pit_rkes <- read_csv("../data/rookie-pitcher.csv")
df_pos_rkes <- read_csv("../data/rookie-position.csv")
# Load retirees datasets
df_pit_ret <- read_csv("../data/retirees-pitcher.csv")
df_pos_ret <- read_csv("../data/retirees-position.csv")
# Find number of retirees by year
num_retirees <- total_retirees_by_yr(df_pit_ret, df_pos_ret)
num_retirees <- data.frame(retirees = num_retirees$retirees)
```

```{r}
#==============================#
#       Position Players       #
#==============================#
# Obtain wrangled datasets
pos_rkes <- wrangle_init(df_pos_rkes)
pos_ret <- wrangle_init(df_pos_ret)
# Get thresholds in each year
pos_rkes_thresholds <- find_thresholds(pos_rkes)
# See and record which players cross that year's threshold
pos_ret <- compare_thresholds(pos_ret, pos_rkes_thresholds)
```

\newpage

## Predicting WAR

```{r}

## Smooth out the coefficient instability by potentially using adjacent year median information to stabliize the threshold value. Potentially add a weight vector to stabilize accordingly. Try 1-2 adjcenent year information, considering edge cases on the boundary (5 forward on left edge and 5 behind on right edge)

# Create list of datasets for ease of function input
ls_datasets <- list(df_pos_rkes, df_pos_ret, df_pit_rkes, df_pit_ret, num_retirees)
# Obtain number of couldabeens given some threshold (in standard deviations)
#couldabeens <- couldabeens_by_threshold(ls_datasets, threshold = 0)
```

```{r}
# setup chunks
knitr::opts_chunk$set(echo = T, fig.align = "center", warning = F, message = F, fig.height = 4)
```

```{r}
# Simpler implementation?
#plot + stat_smooth(mapping = aes(x = Year, y = prop), data = couldabeens_post, method = "lm", formula = prop ~ Year, se = F)
```

```{r}
#pitchers <- df_pit_rkes
#pitchers1 <- drop_na(pitchers)
#pitchers1_trn <- pitchers1 %>% sample_frac(0.7)
#pitchers1_tst <- pitchers1 %>% anti_join(pitchers1_trn)
```

```{r}
#library(leaps)
#ss1 <- regsubsets(WAR~. - Rk - Player, data = pitchers1_trn, nvmax = 49, method = "forward")
```

```{r}
# remove troublesome variables
wrangle_lm <- function(dataset){
  dataset[,-c(1,2,5,6,7,8,25,26)] %>% drop_na()
}
dataset <- wrangle_lm(df_pit_rkes) 
# select significant variables
select_vars <- function(dataset){
  dataset[,c(1,3,4,12,13,14,19,26,30,32,37,38,40)] %>% drop_na()
}
pitchers <- select_vars(dataset) 
```

```{r}
pitchers_trn <-  pitchers %>% sample_frac(0.7)
pitchers_tst <- pitchers %>% anti_join(pitchers_trn)
```

```{r}
linear_model <- lm(WAR ~ ., data = pitchers)
summary(linear_model)
plot(linear_model)
```

```{r}
predictions <- predict(linear_model, pitchers_tst)
test_MSE <- mean(predictions - pitchers_tst$WAR)^2
test_MSE
```


```{r}
#data.frame(model = 1:50, adjr2 = summary(ss1)$adjr2, rss = summary(ss1)$rss, cp = summary(ss1)$cp)%>% arrange(desc(cp))
```


